import {describe,it,expect} from 'vitest';
import {chipRegions,chipSvg,defaultChip,parseChip,validChip} from './chip';
import {unionOutline} from './outlineUnion';
describe('chip constructions',()=>{
 it('generates complete repeatable variations on the chosen grid',()=>{const a=chipRegions(defaultChip);expect(a.length).toBeGreaterThan(10);expect(a).toEqual(chipRegions(defaultChip));expect(a).not.toEqual(chipRegions({...defaultChip,seed:1249}));for(const grid of [2,5,7.5,10])for(const p of chipRegions({...defaultChip,traditional:false,grid}).flat()){expect(p.x/grid).toBeCloseTo(Math.round(p.x/grid),8);expect(p.y/grid).toBeCloseTo(Math.round(p.y/grid),8);}});
 it('retains edited corners in saved layouts and SVG',()=>{const points=chipRegions(defaultChip)[0].map(p=>({x:p.x+5,y:p.y})),s={...defaultChip,edits:{0:points}};expect(chipRegions(parseChip(JSON.stringify(s)))[0]).toEqual(points);expect(chipSvg(s)).not.toEqual(chipSvg(defaultChip));});
 it('rejects invalid seed, grid and corner imports',()=>{for(const extra of [{seed:-1},{seed:Infinity},{grid:0},{grid:1000},{edits:{0:[{x:NaN,y:0}]}},{edits:{0:[{x:-1,y:5},{x:5,y:10},{x:10,y:5}]}}])expect(()=>parseChip(JSON.stringify({...defaultChip,...extra}))).toThrow();});
 it('rejects collapsed and self-crossing chip edits',()=>{expect(validChip([{x:0,y:0},{x:5,y:5},{x:10,y:10}])).toBe(false);expect(validChip([{x:0,y:0},{x:10,y:10},{x:10,y:0},{x:0,y:10}])).toBe(false);for(const p of chipRegions(defaultChip))expect(validChip(p)).toBe(true);});
 it('keeps every generated region inside its physical page',()=>{for(const family of ['rosette','star','border'] as const)for(const count of [4,6,8,12,16]){const s={...defaultChip,family,count};for(const p of chipRegions(s).flat()){expect(p.x).toBeGreaterThanOrEqual(0);expect(p.y).toBeGreaterThanOrEqual(0);expect(p.x).toBeLessThanOrEqual(s.size);expect(p.y).toBeLessThanOrEqual(s.size);}}});
 it('exports only retained closed regions',()=>{const s={...defaultChip,removed:[0,2]};expect(chipSvg(s).match(/<path /g)?.length).toBe(chipRegions(s).length-2);expect(chipSvg(s)).toContain('100mm');expect(chipSvg(s)).not.toContain('dasharray');expect(parseChip(JSON.stringify(s))).toEqual(s);expect(()=>parseChip(JSON.stringify({...s,count:999}))).toThrow();});
 it('removes the shared seam of adjacent rectangles',()=>{const a=[{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10}],b=a.map(p=>({x:p.x+10,y:p.y}));const d=unionOutline([a,b]);expect(d).not.toContain('10.000 0.000 L 10.000 10.000');expect(d).not.toContain('10.000 10.000 L 10.000 0.000');expect(d).toContain('20.000');});
});
