import {Presets} from './Presets';
import {useState,useEffect,useRef,type PointerEvent} from 'react';
import {chipRegions,chipSvg,defaultChip,parseChip,validChip,type ChipSettings,type ChipFamily} from './chip';
import {polyPath} from './outlineUnion';
import type {Point} from './geometry';
import {borderNames} from './chipBorders';
import {chipHandles,moveChipHandle} from './chipHandles';
export function ChipBuilder({back}:{back:()=>void}){
 const [settings,setSettings]=useState<ChipSettings>(()=>{try{return parseChip(localStorage.getItem('carve-chip-grid-v2')??'null');}catch{return defaultChip;}}),[grid,setGrid]=useState(true),[past,setPast]=useState<ChipSettings[]>([]),[status,setStatus]=useState('Saved on this device'),[selected,setSelected]=useState<number|null>(null);
 const svg=useRef<SVGSVGElement>(null),drag=useRef<{id:number;vertex?:number;start:Point;before:ChipSettings;points:Point[]}|null>(null),file=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{localStorage.setItem('carve-chip-grid-v2',JSON.stringify(settings));}catch{setStatus('Auto-save unavailable. Save the editable pattern before closing.');}},[settings]);
 function change(s:ChipSettings){setPast(p=>[...p,settings].slice(-60));setSettings(s);}
 const regions=chipRegions(settings),step=settings.grid??5;
 function point(e:PointerEvent):Point{const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.current!.getScreenCTM()!.inverse());return {x:p.x,y:p.y};}
 function start(e:PointerEvent,id:number,vertex?:number){if(e.button!==0)return;e.stopPropagation();setSelected(id);drag.current={id,vertex,start:point(e),before:settings,points:regions[id]};svg.current!.setPointerCapture(e.pointerId);}
 function move(e:PointerEvent){const d=drag.current;if(!d)return;const p=point(e),snap=(n:number)=>Math.round(n/step)*step,dx=snap(p.x-d.start.x),dy=snap(p.y-d.start.y);
  const points=d.vertex===undefined?d.points.map(q=>({x:q.x+dx,y:q.y+dy})):moveChipHandle(d.points,d.vertex,{x:snap(p.x),y:snap(p.y)});
  if(points.some(q=>q.x<0||q.y<0||q.x>settings.size||q.y>settings.size)||!validChip(points))return;
  setSettings({...d.before,edits:{...d.before.edits,[d.id]:points}});
 }
 function end(e:PointerEvent,cancel=false){const d=drag.current;if(!d)return;drag.current=null;if(svg.current?.hasPointerCapture(e.pointerId))svg.current.releasePointerCapture(e.pointerId);if(cancel)setSettings(d.before);else if(JSON.stringify(d.before)!==JSON.stringify(settings))setPast(p=>[...p,d.before].slice(-60));}
 function save(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <div className="wb"><header className="wb-header"><div><span className="wb-eyebrow">ScrollWorks / CHIP CARVING</span><h1>Chip pattern generator</h1></div><div className="wb-header-actions"><button onClick={back}>Back to scrollwork</button><button onClick={()=>file.current?.click()}>Open chip layout</button><button onClick={()=>save('chip-layout.json',JSON.stringify(settings,null,2),'application/json')}>Save chip layout</button><button className="wb-primary" onClick={()=>save('chip-pattern.svg',chipSvg(settings),'image/svg+xml')}>Export chip SVG</button><input hidden ref={file} type="file" accept=".json" onChange={async e=>{const input=e.currentTarget,f=input.files?.[0];if(!f)return;try{change(parseChip(await f.text()));setSelected(null);setStatus('Chip layout opened.');}catch{setStatus('Could not open this chip layout.');}input.value='';}}/></div></header>
 <div className="wb-body" style={{gridTemplateColumns:'260px minmax(0,1fr)'}}><aside className="wb-inspector"><Presets kind="chip" value={settings} validate={parseChip} preview={chipSvg} load={next=>{change(next);setSelected(null);}}/><h2>Generate a complete pattern</h2><p>One seed chooses a center, border rhythm and corner treatment. Generate variation applies the new composition rules. Edit afterward on the millimeter grid.</p><label className="wb-check">Composition <select aria-label="Chip pattern" value={settings.family} onChange={e=>{change({...settings,family:e.target.value as ChipFamily,traditional:true,grammar:2,borderVersion:1,grid:step,removed:[],edits:{}});setSelected(null);}}><option value="star">Faceted center and running border</option><option value="rosette">Compass petals and running border</option><option value="border">Border frame</option></select></label>
 <p>Variation {settings.seed??1248}</p><button className="wb-primary" onClick={()=>{change({...settings,seed:((settings.seed??1248)+1)>>>0,traditional:true,grammar:2,borderVersion:1,grid:step,removed:[],edits:{}});setSelected(null);}}>Generate variation</button><p>Border: {settings.traditional?['Linked petals','Alternating fans','Curved facet chain'][(settings.borderSeed??settings.seed??1248)%3]:settings.borderVersion===1?borderNames[(settings.borderSeed??settings.seed??1248)%6]:'Earlier border — vary to update'}</p><button onClick={()=>{change({...settings,traditional:true,grammar:2,borderVersion:1,grid:step,borderSeed:((settings.borderSeed??settings.seed??1248)+1)>>>0,removed:[],edits:{}});setSelected(null);}}>Vary border only</button><p>Border variations keep the generated center. Generating clears manual edits; Undo restores them.</p>
 <label className="wb-check">Grid interval (mm)<input aria-label="Grid interval" type="number" min="2" max={Math.min(30,settings.size/6)} step="1" value={step} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n)&&n>=2&&n<=Math.min(30,settings.size/6)){change({...settings,traditional:true,grammar:2,borderVersion:1,grid:n,removed:[],edits:{}});setSelected(null);}}}/></label><label className="wb-check">Page (mm)<input aria-label="Chip page size" type="number" min="40" max="300" value={settings.size} onChange={e=>{const n=e.target.valueAsNumber;if(Number.isFinite(n)&&n>=40&&n<=300){change({...settings,traditional:true,grammar:2,borderVersion:1,size:n,grid:Math.min(step,Math.floor(n/6)),removed:[],edits:{}});setSelected(null);}}}/></label><label className="wb-check"><input type="checkbox" checked={grid} onChange={e=>setGrid(e.target.checked)}/> Show millimeter grid</label><p>The grid sets construction size and snaps manual edits. Circular sectors and curved outlines retain their natural geometry.</p>
 <h2>Edit on the grid</h2><p>Drag a chip to move it. Curved pieces have Start, Middle and End handles; dragging one bends the whole curve. Review overlaps after editing.</p><div className="wb-pair"><button disabled={!past.length} onClick={()=>{setSettings(past.at(-1)!);setPast(p=>p.slice(0,-1));setSelected(null);}}>Undo edit</button><button disabled={selected===null} onClick={()=>{if(selected!==null){change({...settings,removed:[...settings.removed,selected]});setSelected(null);}}}>Remove chip</button></div><button onClick={()=>change({...settings,removed:[]})}>Restore removed chips</button><p>SVG contains retained outlines at actual size. The editing grid stays out of the export.</p></aside>
 <main className="wb-workspace"><p className="wb-hint">{selected===null?'Generate a variation, then select a chip to edit its handles.':`Chip ${selected+1} selected · drag its handles or move the whole chip · edits snap to ${step} mm`}</p><div className="wb-paper-wrap"><svg ref={svg} className="wb-paper" style={{maxHeight:'75vh',aspectRatio:'1'}} viewBox={`0 0 ${settings.size} ${settings.size}`} aria-label="Chip pattern canvas" onPointerMove={move} onPointerUp={e=>end(e)} onPointerCancel={e=>end(e,true)}><defs><pattern id="chip-grid" width={step} height={step} patternUnits="userSpaceOnUse"><path d={`M ${step} 0 L 0 0 0 ${step}`} fill="none" stroke="#9cb1a5" strokeWidth=".15"/></pattern></defs>{grid&&<rect width={settings.size} height={settings.size} fill="url(#chip-grid)" pointerEvents="none"/>}
 {regions.map((p,i)=>settings.removed.includes(i)?null:<path key={i} d={polyPath(p,true)} role="button" tabIndex={0} aria-label={`Chip ${i+1}`} aria-pressed={selected===i} fill={selected===i?'#d3e6da':'#eaf0eac9'} stroke="#151a16" strokeWidth=".25" style={{cursor:'move'}} onPointerDown={e=>start(e,i)} onKeyDown={e=>{if(e.key==='Enter')setSelected(i);if(e.key==='Delete'){change({...settings,removed:[...settings.removed,i]});setSelected(null);}}}/>)}
 {selected!==null&&regions[selected]&&chipHandles(regions[selected]).map(({point:p,index,label})=><circle key={index} aria-label={label} cx={p.x} cy={p.y} r={Math.max(.65,settings.size*.005)} fill="#fff" stroke="#286b55" strokeWidth=".3" style={{cursor:'crosshair'}} onPointerDown={e=>start(e,selected,index)}><title>{label}</title></circle>)}
 </svg></div><div className="wb-footer"><span>{settings.size} × {settings.size} mm · {step} mm grid · {regions.filter((_,i)=>!settings.removed.includes(i)).length} chips</span><span role="status">{status}</span></div></main></div></div>;
}


