import {useState} from 'react';
type Entry<T>={id:string;name:string;data:T;image:string};
export function Presets<T>({kind,value,validate,preview,load}:{kind:string;value:T;validate:(s:string)=>T;preview:(v:T)=>string;load:(v:T)=>void}){
 const key=`ruffensteint-presets-${kind}-v1`;
 const [entries,setEntries]=useState<Entry<T>[]>(()=>{try{const raw=JSON.parse(localStorage.getItem(key)??'[]');return raw.slice(0,40).filter((e:Entry<T>)=>{try{validate(JSON.stringify(e.data));return typeof e.id==='string'&&typeof e.name==='string'&&typeof e.image==='string';}catch{return false;}});}catch{return [];}});
 const [name,setName]=useState(''),[selected,setSelected]=useState(''),[message,setMessage]=useState(''),[deleted,setDeleted]=useState<Entry<T>|null>(null);
 function save(next:Entry<T>[]){try{localStorage.setItem(key,JSON.stringify(next));setEntries(next);return true;}catch{setMessage('Device storage is full. Remove a preset or save a file backup.');return false;}}
 function add(data:T,image?:string){if(entries.length>=40){setMessage('Library holds 40 presets. Remove one before adding another.');return;}const title=name.trim()||`${kind==='scroll'?'Scroll':'Chip'} ${entries.length+1}`,id=crypto.randomUUID();if(save([...entries,{id,name:title.slice(0,80),data:validate(JSON.stringify(data)),image:image??preview(data)}])){setSelected(id);setName(title);setMessage('Preset saved on this device.');}}
 return <details className="preset-library"><summary>My presets · {entries.length}</summary><label>Preset name<input value={name} maxLength={80} onChange={e=>setName(e.target.value)} placeholder="Name this design"/></label><button onClick={()=>add(value)}>Save current design</button><div className="preset-cards">{entries.map(e=><button key={e.id} aria-pressed={selected===e.id} onClick={()=>{load(validate(JSON.stringify(e.data)));setSelected(e.id);setName(e.name);setMessage('Preset loaded. Undo returns to your previous design.');}}><img src={`data:image/svg+xml,${encodeURIComponent(e.image)}`} alt=""/><span>{e.name}</span></button>)}</div>{selected&&<div className="preset-actions"><button onClick={()=>{if(name.trim())save(entries.map(e=>e.id===selected?{...e,name:name.trim().slice(0,80)}:e));}}>Rename</button><button onClick={()=>{const e=entries.find(e=>e.id===selected);if(e)add(e.data,e.image);}}>Duplicate</button><button onClick={()=>{const e=entries.find(e=>e.id===selected);if(e&&save(entries.filter(e=>e.id!==selected))){setDeleted(e);setSelected('');}}}>Delete</button></div>}{deleted&&<button onClick={()=>{if(entries.length<40&&save([...entries,deleted]))setDeleted(null);}}>Undo preset deletion</button>}<p role="status">{message}</p><small>Stored on this device. Save layout files for backups.</small></details>;
}
